# #####################################################################
# Automatically generated by qmake (2.01a) Mon Nov 24 21:22:37 2008
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
ICON = icon.icns
QT += webkit \
    network

# Input
HEADERS += htmlHighlighter.h \
    page.h \
    preferences.h \
    workbench.h \
    filesystem.h
FORMS += preferences.ui \
    workbench.ui \
    filesystem.ui
SOURCES += htmlHighlighter.cpp \
    main.cpp \
    preferences.cpp \
    workbench.cpp \
    filesystem.cpp
RESOURCES += resources.qrc
