# #####################################################################
# Automatically generated by qmake (2.01a) Wed 1. Jul 12:22:21 2009
# #####################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += FtpDirModel.h FtpDirModel_p.h 
SOURCES += FtpDirModel.cpp FtpDirModel_p.cpp Main.cpp
QT      += network

